### PR TITLE
Bump to 1.1.2 for release

### PR DESCRIPTION
**Pull request by caplan**
@thiagopnts @Veronique please review

### CODE REVIEW

**Comment by Veronique** [comment]
@caplan You don't need approval for versioning a pod. Please refer to these instructions for the full process: https://github.com/nytm/ios-podspecs/wiki/Releasing-A-New-Version-Of-A-Pod

**Comment by caplan** [comment]
I don't have permissions for step 2, `Merge it yourself immediately`

**Comment by Veronique** [comment]
I merged it for you. Are you able to continue with the process of release a new version?

**Comment by Veronique** [comment]
I also closed this issue: https://github.com/NYTimes/ios-360-videos/issues/58

**Comment by caplan** [comment]
Unfortunately I cannot create a new release either.

**Comment by yorkepb** [comment]
@caplan I just gave you access to this repo. So you should be good now.

**Pull request merged**
